#!/bin/sh
# see http://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-whitespace-before-committing/4597057#4597057
# put this in .git/hooks/pre-commit or .../git-core/templates/hooks
#  (... depends on where your git is installed... could be /usr/share or /usr/local/git/share or /opt/local/git/share or ...?)
# run "git init" in your existing repos to get it in there

if git-rev-parse --verify HEAD >/dev/null 2>&1 ; then
   against=HEAD
else
   # Initial commit: diff against an empty tree object
   against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Find files with trailing whitespace
for FILE in `exec git diff-index --check --cached $against -- | sed '/^[+-]/d' | sed -E 's/:[0-9]+:.*//' | uniq` ; do
    # Fix them!
    sed -i '' -E 's/[[:space:]]*$//' "$FILE"
    git add "$FILE"
done

